################################################################################
##   Cooling Routes
################################################################################

### Requests Cooling monitor data
GET http://localhost:5000/cooling
