const Disclaimer = '<strong><span class="text-decoration-underline">SEE USER OPERATIONS MANUAL FOR IMPORTANT LIFE AND EQUIPMENT SAFETY INFORMATION.</span> THIS EQUIPMENT SHOULD BE MAINTAINED IN ACCORDANCE WITH THE USER OPERATIONS MANUAL, AND OPERATED AND SERVICED ONLY BY TRAINED AND QUALIFIED PERSONNEL.</strong> PROTECTED BY UNITED STATES AND INTERNATIONAL PATENTS PENDING. INCLUDES SOFTWARE COPYRIGHT© TMGcore AND SUBJECT TO END USER LICENSE AGREEMENT. CONTACT TMGcore FOR COPIES OF MANUALS, LICENSE AGREEMENTS AND OTHER MATERIALS. ALL RIGHTS RESERVED.';

Object.freeze(Disclaimer);

module.exports = Disclaimer;
