################################################################################
##   Express
################################################################################
### Express Root - HTTP
GET http://localhost:5000

### Express About - HTTP
GET http://localhost:5000/redis/set/helloworld
